// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: Protobuf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbMessage_CMD int32

const (
	PbMessage_Login        PbMessage_CMD = 0
	PbMessage_match        PbMessage_CMD = 1
	PbMessage_matchConfirm PbMessage_CMD = 2
)

// Enum value maps for PbMessage_CMD.
var (
	PbMessage_CMD_name = map[int32]string{
		0: "Login",
		1: "match",
		2: "matchConfirm",
	}
	PbMessage_CMD_value = map[string]int32{
		"Login":        0,
		"match":        1,
		"matchConfirm": 2,
	}
)

func (x PbMessage_CMD) Enum() *PbMessage_CMD {
	p := new(PbMessage_CMD)
	*p = x
	return p
}

func (x PbMessage_CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbMessage_CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_proto_enumTypes[0].Descriptor()
}

func (PbMessage_CMD) Type() protoreflect.EnumType {
	return &file_Protobuf_proto_enumTypes[0]
}

func (x PbMessage_CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbMessage_CMD.Descriptor instead.
func (PbMessage_CMD) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{0, 0}
}

type PbMessage_RoomState int32

const (
	PbMessage_none         PbMessage_RoomState = 0
	PbMessage_confirm      PbMessage_RoomState = 1
	PbMessage_select       PbMessage_RoomState = 2
	PbMessage_loadResource PbMessage_RoomState = 3
	PbMessage_fight        PbMessage_RoomState = 4
	PbMessage_end          PbMessage_RoomState = 5
)

// Enum value maps for PbMessage_RoomState.
var (
	PbMessage_RoomState_name = map[int32]string{
		0: "none",
		1: "confirm",
		2: "select",
		3: "loadResource",
		4: "fight",
		5: "end",
	}
	PbMessage_RoomState_value = map[string]int32{
		"none":         0,
		"confirm":      1,
		"select":       2,
		"loadResource": 3,
		"fight":        4,
		"end":          5,
	}
)

func (x PbMessage_RoomState) Enum() *PbMessage_RoomState {
	p := new(PbMessage_RoomState)
	*p = x
	return p
}

func (x PbMessage_RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbMessage_RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_proto_enumTypes[1].Descriptor()
}

func (PbMessage_RoomState) Type() protoreflect.EnumType {
	return &file_Protobuf_proto_enumTypes[1]
}

func (x PbMessage_RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbMessage_RoomState.Descriptor instead.
func (PbMessage_RoomState) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{0, 1}
}

// this is a comment
type PbMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd           PbMessage_CMD       `protobuf:"varint,2,opt,name=cmd,proto3,enum=pb.PbMessage_CMD" json:"cmd,omitempty"`
	IsRoomMessage bool                `protobuf:"varint,3,opt,name=isRoomMessage,proto3" json:"isRoomMessage,omitempty"`
	SetRoomState  PbMessage_RoomState `protobuf:"varint,4,opt,name=setRoomState,proto3,enum=pb.PbMessage_RoomState" json:"setRoomState,omitempty"`
	Sid           uint32              `protobuf:"varint,5,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *PbMessage) Reset() {
	*x = PbMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMessage) ProtoMessage() {}

func (x *PbMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMessage.ProtoReflect.Descriptor instead.
func (*PbMessage) Descriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *PbMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbMessage) GetCmd() PbMessage_CMD {
	if x != nil {
		return x.Cmd
	}
	return PbMessage_Login
}

func (x *PbMessage) GetIsRoomMessage() bool {
	if x != nil {
		return x.IsRoomMessage
	}
	return false
}

func (x *PbMessage) GetSetRoomState() PbMessage_RoomState {
	if x != nil {
		return x.SetRoomState
	}
	return PbMessage_none
}

func (x *PbMessage) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

var File_Protobuf_proto protoreflect.FileDescriptor

var file_Protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0xbe, 0x02, 0x0a, 0x09, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69,
	0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0c, 0x73, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x22, 0x2d, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x22,
	0x54, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x10,
	0x03, 0x12, 0x09, 0x0a, 0x05, 0x66, 0x69, 0x67, 0x68, 0x74, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x10, 0x05, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Protobuf_proto_rawDescOnce sync.Once
	file_Protobuf_proto_rawDescData = file_Protobuf_proto_rawDesc
)

func file_Protobuf_proto_rawDescGZIP() []byte {
	file_Protobuf_proto_rawDescOnce.Do(func() {
		file_Protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protobuf_proto_rawDescData)
	})
	return file_Protobuf_proto_rawDescData
}

var file_Protobuf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_proto_goTypes = []interface{}{
	(PbMessage_CMD)(0),       // 0: pb.PbMessage.CMD
	(PbMessage_RoomState)(0), // 1: pb.PbMessage.RoomState
	(*PbMessage)(nil),        // 2: pb.PbMessage
}
var file_Protobuf_proto_depIdxs = []int32{
	0, // 0: pb.PbMessage.cmd:type_name -> pb.PbMessage.CMD
	1, // 1: pb.PbMessage.setRoomState:type_name -> pb.PbMessage.RoomState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Protobuf_proto_init() }
func file_Protobuf_proto_init() {
	if File_Protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protobuf_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_proto_goTypes,
		DependencyIndexes: file_Protobuf_proto_depIdxs,
		EnumInfos:         file_Protobuf_proto_enumTypes,
		MessageInfos:      file_Protobuf_proto_msgTypes,
	}.Build()
	File_Protobuf_proto = out.File
	file_Protobuf_proto_rawDesc = nil
	file_Protobuf_proto_goTypes = nil
	file_Protobuf_proto_depIdxs = nil
}
