// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: Protobuf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbMessage_CMD int32

const (
	PbMessage_clickLogin PbMessage_CMD = 0
	PbMessage_match      PbMessage_CMD = 1
	PbMessage_roomInit   PbMessage_CMD = 2
	PbMessage_confirm    PbMessage_CMD = 3
	PbMessage_select     PbMessage_CMD = 4
	PbMessage_load       PbMessage_CMD = 5
	PbMessage_fightStart PbMessage_CMD = 6
)

// Enum value maps for PbMessage_CMD.
var (
	PbMessage_CMD_name = map[int32]string{
		0: "clickLogin",
		1: "match",
		2: "roomInit",
		3: "confirm",
		4: "select",
		5: "load",
		6: "fightStart",
	}
	PbMessage_CMD_value = map[string]int32{
		"clickLogin": 0,
		"match":      1,
		"roomInit":   2,
		"confirm":    3,
		"select":     4,
		"load":       5,
		"fightStart": 6,
	}
)

func (x PbMessage_CMD) Enum() *PbMessage_CMD {
	p := new(PbMessage_CMD)
	*p = x
	return p
}

func (x PbMessage_CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbMessage_CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_proto_enumTypes[0].Descriptor()
}

func (PbMessage_CMD) Type() protoreflect.EnumType {
	return &file_Protobuf_proto_enumTypes[0]
}

func (x PbMessage_CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbMessage_CMD.Descriptor instead.
func (PbMessage_CMD) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{3, 0}
}

type PbMessage_Match int32

const (
	PbMessage_joinMatch PbMessage_Match = 0
	PbMessage_quitMatch PbMessage_Match = 1
)

// Enum value maps for PbMessage_Match.
var (
	PbMessage_Match_name = map[int32]string{
		0: "joinMatch",
		1: "quitMatch",
	}
	PbMessage_Match_value = map[string]int32{
		"joinMatch": 0,
		"quitMatch": 1,
	}
)

func (x PbMessage_Match) Enum() *PbMessage_Match {
	p := new(PbMessage_Match)
	*p = x
	return p
}

func (x PbMessage_Match) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbMessage_Match) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_proto_enumTypes[1].Descriptor()
}

func (PbMessage_Match) Type() protoreflect.EnumType {
	return &file_Protobuf_proto_enumTypes[1]
}

func (x PbMessage_Match) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbMessage_Match.Descriptor instead.
func (PbMessage_Match) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{3, 1}
}

// this is a comment
type PlayerSelectData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//具体的阵营选择还没写
	Faction       int32 `protobuf:"varint,4,opt,name=faction,proto3" json:"faction,omitempty"`
	IsSelectDone  bool  `protobuf:"varint,5,opt,name=isSelectDone,proto3" json:"isSelectDone,omitempty"`
	AllSelectDone bool  `protobuf:"varint,6,opt,name=allSelectDone,proto3" json:"allSelectDone,omitempty"`
}

func (x *PlayerSelectData) Reset() {
	*x = PlayerSelectData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerSelectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSelectData) ProtoMessage() {}

func (x *PlayerSelectData) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSelectData.ProtoReflect.Descriptor instead.
func (*PlayerSelectData) Descriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerSelectData) GetFaction() int32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *PlayerSelectData) GetIsSelectDone() bool {
	if x != nil {
		return x.IsSelectDone
	}
	return false
}

func (x *PlayerSelectData) GetAllSelectDone() bool {
	if x != nil {
		return x.AllSelectDone
	}
	return false
}

type PlayerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaySid            int32             `protobuf:"varint,1,opt,name=playSid,proto3" json:"playSid,omitempty"`
	RoomId             int32             `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerName         string            `protobuf:"bytes,3,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerIndex        int32             `protobuf:"varint,4,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	IsConfirmed        bool              `protobuf:"varint,5,opt,name=isConfirmed,proto3" json:"isConfirmed,omitempty"`
	PlayerSelectData   *PlayerSelectData `protobuf:"bytes,6,opt,name=playerSelectData,proto3" json:"playerSelectData,omitempty"`
	IsReady            bool              `protobuf:"varint,7,opt,name=isReady,proto3" json:"isReady,omitempty"`
	LoadPercent        int32             `protobuf:"varint,8,opt,name=loadPercent,proto3" json:"loadPercent,omitempty"`
	IsLoadResourceDone bool              `protobuf:"varint,9,opt,name=isLoadResourceDone,proto3" json:"isLoadResourceDone,omitempty"`
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerData) GetPlaySid() int32 {
	if x != nil {
		return x.PlaySid
	}
	return 0
}

func (x *PlayerData) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PlayerData) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerData) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *PlayerData) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

func (x *PlayerData) GetPlayerSelectData() *PlayerSelectData {
	if x != nil {
		return x.PlayerSelectData
	}
	return nil
}

func (x *PlayerData) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *PlayerData) GetLoadPercent() int32 {
	if x != nil {
		return x.LoadPercent
	}
	return 0
}

func (x *PlayerData) GetIsLoadResourceDone() bool {
	if x != nil {
		return x.IsLoadResourceDone
	}
	return false
}

type RoomPlayersData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerData          []*PlayerData `protobuf:"bytes,1,rep,name=playerData,proto3" json:"playerData,omitempty"`
	AllConfirmed        bool          `protobuf:"varint,2,opt,name=allConfirmed,proto3" json:"allConfirmed,omitempty"`
	AllReady            bool          `protobuf:"varint,3,opt,name=allReady,proto3" json:"allReady,omitempty"`
	AllLoadResourceDone bool          `protobuf:"varint,4,opt,name=allLoadResourceDone,proto3" json:"allLoadResourceDone,omitempty"`
}

func (x *RoomPlayersData) Reset() {
	*x = RoomPlayersData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayersData) ProtoMessage() {}

func (x *RoomPlayersData) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayersData.ProtoReflect.Descriptor instead.
func (*RoomPlayersData) Descriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *RoomPlayersData) GetPlayerData() []*PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *RoomPlayersData) GetAllConfirmed() bool {
	if x != nil {
		return x.AllConfirmed
	}
	return false
}

func (x *RoomPlayersData) GetAllReady() bool {
	if x != nil {
		return x.AllReady
	}
	return false
}

func (x *RoomPlayersData) GetAllLoadResourceDone() bool {
	if x != nil {
		return x.AllLoadResourceDone
	}
	return false
}

type PbMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd             PbMessage_CMD    `protobuf:"varint,2,opt,name=cmd,proto3,enum=pb.PbMessage_CMD" json:"cmd,omitempty"`
	CmdMatch        PbMessage_Match  `protobuf:"varint,8,opt,name=cmdMatch,proto3,enum=pb.PbMessage_Match" json:"cmdMatch,omitempty"`
	PlayerData      *PlayerData      `protobuf:"bytes,3,opt,name=playerData,proto3" json:"playerData,omitempty"`
	RoomPlayersData *RoomPlayersData `protobuf:"bytes,4,opt,name=roomPlayersData,proto3" json:"roomPlayersData,omitempty"`
	Sid             uint32           `protobuf:"varint,7,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *PbMessage) Reset() {
	*x = PbMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMessage) ProtoMessage() {}

func (x *PbMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMessage.ProtoReflect.Descriptor instead.
func (*PbMessage) Descriptor() ([]byte, []int) {
	return file_Protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *PbMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbMessage) GetCmd() PbMessage_CMD {
	if x != nil {
		return x.Cmd
	}
	return PbMessage_clickLogin
}

func (x *PbMessage) GetCmdMatch() PbMessage_Match {
	if x != nil {
		return x.CmdMatch
	}
	return PbMessage_joinMatch
}

func (x *PbMessage) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *PbMessage) GetRoomPlayersData() *RoomPlayersData {
	if x != nil {
		return x.RoomPlayersData
	}
	return nil
}

func (x *PbMessage) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

var File_Protobuf_proto protoreflect.FileDescriptor

var file_Protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x76, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x6f,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61,
	0x6c, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0xd0, 0x02, 0x0a,
	0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x53, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x53, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65,
	0x64, 0x12, 0x40, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x12, 0x69, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x69, 0x73, 0x4c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x22,
	0xb3, 0x01, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x12, 0x30, 0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x13, 0x61, 0x6c, 0x6c, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0x80, 0x03, 0x0a, 0x09, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x08,
	0x63, 0x6d, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x08, 0x63, 0x6d, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2e, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a,
	0x0f, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x72, 0x6f, 0x6f,
	0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x61,
	0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x10,
	0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x66, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10,
	0x06, 0x22, 0x25, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0d, 0x0a, 0x09, 0x6a, 0x6f,
	0x69, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x71, 0x75, 0x69,
	0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Protobuf_proto_rawDescOnce sync.Once
	file_Protobuf_proto_rawDescData = file_Protobuf_proto_rawDesc
)

func file_Protobuf_proto_rawDescGZIP() []byte {
	file_Protobuf_proto_rawDescOnce.Do(func() {
		file_Protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protobuf_proto_rawDescData)
	})
	return file_Protobuf_proto_rawDescData
}

var file_Protobuf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Protobuf_proto_goTypes = []interface{}{
	(PbMessage_CMD)(0),       // 0: pb.PbMessage.CMD
	(PbMessage_Match)(0),     // 1: pb.PbMessage.Match
	(*PlayerSelectData)(nil), // 2: pb.PlayerSelectData
	(*PlayerData)(nil),       // 3: pb.PlayerData
	(*RoomPlayersData)(nil),  // 4: pb.RoomPlayersData
	(*PbMessage)(nil),        // 5: pb.PbMessage
}
var file_Protobuf_proto_depIdxs = []int32{
	2, // 0: pb.PlayerData.playerSelectData:type_name -> pb.PlayerSelectData
	3, // 1: pb.RoomPlayersData.playerData:type_name -> pb.PlayerData
	0, // 2: pb.PbMessage.cmd:type_name -> pb.PbMessage.CMD
	1, // 3: pb.PbMessage.cmdMatch:type_name -> pb.PbMessage.Match
	3, // 4: pb.PbMessage.playerData:type_name -> pb.PlayerData
	4, // 5: pb.PbMessage.roomPlayersData:type_name -> pb.RoomPlayersData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Protobuf_proto_init() }
func file_Protobuf_proto_init() {
	if File_Protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerSelectData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayersData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protobuf_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_proto_goTypes,
		DependencyIndexes: file_Protobuf_proto_depIdxs,
		EnumInfos:         file_Protobuf_proto_enumTypes,
		MessageInfos:      file_Protobuf_proto_msgTypes,
	}.Build()
	File_Protobuf_proto = out.File
	file_Protobuf_proto_rawDesc = nil
	file_Protobuf_proto_goTypes = nil
	file_Protobuf_proto_depIdxs = nil
}
