// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protobuf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Protobuf.proto</summary>
  public static partial class ProtobufReflection {

    #region Descriptor
    /// <summary>File descriptor for Protobuf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtobufReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2J1Zi5wcm90bxICcGIikQIKCVBiTWVzc2FnZRIMCgRuYW1lGAEg",
            "ASgJEh4KA2NtZBgCIAEoDjIRLnBiLlBiTWVzc2FnZS5DTUQSFQoNaXNSb29t",
            "TWVzc2FnZRgDIAEoCBItCgxzZXRSb29tU3RhdGUYBCABKA4yFy5wYi5QYk1l",
            "c3NhZ2UuUm9vbVN0YXRlEgsKA3NpZBgFIAEoDSItCgNDTUQSCQoFTG9naW4Q",
            "ABIJCgVtYXRjaBABEhAKDG1hdGNoQ29uZmlybRACIlQKCVJvb21TdGF0ZRII",
            "CgRub25lEAASCwoHY29uZmlybRABEgoKBnNlbGVjdBACEhAKDGxvYWRSZXNv",
            "dXJjZRADEgkKBWZpZ2h0EAQSBwoDZW5kEAVCBloELi9wYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.PbMessage), global::Pb.PbMessage.Parser, new[]{ "Name", "Cmd", "IsRoomMessage", "SetRoomState", "Sid" }, null, new[]{ typeof(global::Pb.PbMessage.Types.CMD), typeof(global::Pb.PbMessage.Types.RoomState) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// this is a comment
  /// </summary>
  public sealed partial class PbMessage : pb::IMessage<PbMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbMessage> _parser = new pb::MessageParser<PbMessage>(() => new PbMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtobufReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage(PbMessage other) : this() {
      name_ = other.name_;
      cmd_ = other.cmd_;
      isRoomMessage_ = other.isRoomMessage_;
      setRoomState_ = other.setRoomState_;
      sid_ = other.sid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage Clone() {
      return new PbMessage(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 2;
    private global::Pb.PbMessage.Types.CMD cmd_ = global::Pb.PbMessage.Types.CMD.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PbMessage.Types.CMD Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "isRoomMessage" field.</summary>
    public const int IsRoomMessageFieldNumber = 3;
    private bool isRoomMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRoomMessage {
      get { return isRoomMessage_; }
      set {
        isRoomMessage_ = value;
      }
    }

    /// <summary>Field number for the "setRoomState" field.</summary>
    public const int SetRoomStateFieldNumber = 4;
    private global::Pb.PbMessage.Types.RoomState setRoomState_ = global::Pb.PbMessage.Types.RoomState.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PbMessage.Types.RoomState SetRoomState {
      get { return setRoomState_; }
      set {
        setRoomState_ = value;
      }
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 5;
    private uint sid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Cmd != other.Cmd) return false;
      if (IsRoomMessage != other.IsRoomMessage) return false;
      if (SetRoomState != other.SetRoomState) return false;
      if (Sid != other.Sid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) hash ^= Cmd.GetHashCode();
      if (IsRoomMessage != false) hash ^= IsRoomMessage.GetHashCode();
      if (SetRoomState != global::Pb.PbMessage.Types.RoomState.None) hash ^= SetRoomState.GetHashCode();
      if (Sid != 0) hash ^= Sid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Cmd);
      }
      if (IsRoomMessage != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRoomMessage);
      }
      if (SetRoomState != global::Pb.PbMessage.Types.RoomState.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) SetRoomState);
      }
      if (Sid != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Cmd);
      }
      if (IsRoomMessage != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRoomMessage);
      }
      if (SetRoomState != global::Pb.PbMessage.Types.RoomState.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) SetRoomState);
      }
      if (Sid != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Sid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Cmd);
      }
      if (IsRoomMessage != false) {
        size += 1 + 1;
      }
      if (SetRoomState != global::Pb.PbMessage.Types.RoomState.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SetRoomState);
      }
      if (Sid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbMessage other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        Cmd = other.Cmd;
      }
      if (other.IsRoomMessage != false) {
        IsRoomMessage = other.IsRoomMessage;
      }
      if (other.SetRoomState != global::Pb.PbMessage.Types.RoomState.None) {
        SetRoomState = other.SetRoomState;
      }
      if (other.Sid != 0) {
        Sid = other.Sid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Cmd = (global::Pb.PbMessage.Types.CMD) input.ReadEnum();
            break;
          }
          case 24: {
            IsRoomMessage = input.ReadBool();
            break;
          }
          case 32: {
            SetRoomState = (global::Pb.PbMessage.Types.RoomState) input.ReadEnum();
            break;
          }
          case 40: {
            Sid = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Cmd = (global::Pb.PbMessage.Types.CMD) input.ReadEnum();
            break;
          }
          case 24: {
            IsRoomMessage = input.ReadBool();
            break;
          }
          case 32: {
            SetRoomState = (global::Pb.PbMessage.Types.RoomState) input.ReadEnum();
            break;
          }
          case 40: {
            Sid = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PbMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum CMD {
        [pbr::OriginalName("Login")] Login = 0,
        [pbr::OriginalName("match")] Match = 1,
        [pbr::OriginalName("matchConfirm")] MatchConfirm = 2,
      }

      public enum RoomState {
        [pbr::OriginalName("none")] None = 0,
        [pbr::OriginalName("confirm")] Confirm = 1,
        [pbr::OriginalName("select")] Select = 2,
        [pbr::OriginalName("loadResource")] LoadResource = 3,
        [pbr::OriginalName("fight")] Fight = 4,
        [pbr::OriginalName("end")] End = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
